<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/16 16:21:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=MAGIC',
  'username' => 'magic',
  'password' => 'magic',
  'name' => 'doctrine',
)),);
