<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Item', 'doctrine');

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $number
 * @property integer $idcard
 * @property integer $idorder
 * @property Card $Card
 * @property Orders $Orders
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method integer getNumber()  Returns the current record's "number" value
 * @method integer getIdcard()  Returns the current record's "idcard" value
 * @method integer getIdorder() Returns the current record's "idorder" value
 * @method Card    getCard()    Returns the current record's "Card" value
 * @method Orders  getOrders()  Returns the current record's "Orders" value
 * @method Item    setId()      Sets the current record's "id" value
 * @method Item    setNumber()  Sets the current record's "number" value
 * @method Item    setIdcard()  Sets the current record's "idcard" value
 * @method Item    setIdorder() Sets the current record's "idorder" value
 * @method Item    setCard()    Sets the current record's "Card" value
 * @method Item    setOrders()  Sets the current record's "Orders" value
 * 
 * @package    themagicgame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcard', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idorder', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Card', array(
             'local' => 'idcard',
             'foreign' => 'id'));

        $this->hasOne('Orders', array(
             'local' => 'idorder',
             'foreign' => 'id'));
    }
}