<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/16 15:55:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=themagicgame',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
