<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/06 13:50:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=MAGIC',
  'username' => 'magic',
  'password' => 'magic',
  'name' => 'doctrine',
)),);
