(function() {
var k=true,m=null,o=false,p=function(a,c,b){this.s=a;this.i=c;this.c=o;this.k=b||m;this.console=window.console||{log:function(){}};if(!this.k&&this.i=="parent")this.console.log("You forgot to pass an iframe.");else{if(!window.UDS_IEXDC_SETUP_COMPLETE)try{window.execScript("Class UDS_GCXPC____NIXVBS_wrapper\n Private UDS_M_TRANSPORT\nPublic Sub UDS_SET_TRANSPORT(transport)\nIf isEmpty(UDS_M_TRANSPORT) Then\nSet UDS_M_TRANSPORT = transport\nEnd If\nEnd Sub\nPublic Sub UDS_SEND_MESSAGE_(payload)\n Call UDS_M_TRANSPORT.UDS_GCXPC____NIXJS_handle_message(payload)\nEnd Sub\nPublic Sub UDS_CREATE_CHANNEL(channel)\n Call UDS_M_TRANSPORT.UDS_GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub UDS_GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function UDS_GCXPC____NIXVBS_get_wrapper(transport)\nDim wrap\nSet wrap = New UDS_GCXPC____NIXVBS_wrapper\nwrap.UDS_SET_TRANSPORT transport\nSet UDS_GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript");window.UDS_IEXDC_SETUP_COMPLETE=k}catch(d){}this.UDS_GCXPC____NIXJS_handle_message=this.q;this.UDS_GCXPC____NIXJS_create_channel=this.p}},r=function(){var a=window.navigator?window.navigator.userAgent:m;return a?a.indexOf("Opera")!=0&&a.indexOf("MSIE")!=-1:o},s=/MSIE\s+([^\);]+)(\)|;)/,u=function(a){return(a=s.exec(a))?a[1]:""};p.prototype.q=function(a){this.i=="parent"&&a=="connected"?this.m():this.s(a)};p.prototype.p=function(a){this.f=a};
var v=function(a,c){return function(){if(!c.c){var b=c.k;try{b.contentWindow.opener=window.UDS_GCXPC____NIXVBS_get_wrapper(c);c.c=k}catch(d){this.console.log("Exception caught while attempting Google IE XDC: "+d.message)}c.c||window.setTimeout(v(c,c),100)}}},w=function(a,c){return function(){if(!c.c){try{var b=window.opener;if(b&&"UDS_GCXPC____NIXVBS_container"in b){c.f=b;c.f.UDS_CREATE_CHANNEL(window.UDS_GCXPC____NIXVBS_get_wrapper(c));c.c=k;c.send("connected");c.m()}}catch(d){return}c.c||window.setTimeout(w(c,
c),100)}}};p.prototype.send=function(a){var c=o;try{this.f.toString()}catch(b){c=k}c?this.f.UDS_SEND_MESSAGE_(a):this.console.log("Cross-domain channel has been modified.")};var x=function(a,c){a.m=c||function(){};a.i=="parent"?v(a,a)():w(a,a)()};function y(a){return parseFloat(a.replace("px",""))||0}
function z(a,c){if(typeof a=="string")a=document.getElementById(a);var b=document.defaultView||{},d=c?a.offsetHeight:a.offsetWidth,g=c?["Top","Bottom"]:["Right","Left"],h=["border","margin","padding"],e=h.length,f=g.length;if(b&&b.getComputedStyle){var n=b.getComputedStyle(a,o);for(b=0;b<e;b++)for(var i=0;i<f;i++)d+=y(n.getPropertyValue([h[b],g[i].toLowerCase()].join("-")))}else{n=a.currentStyle;for(i=0;i<f;i++)d+=y(n[[h[0],g[i],"Width"].join("")]);for(b=1;b<e;b++)for(i=0;i<f;i++)d+=y(n[[h[b],g[i]].join("")])}return d}
;var A=this;var C=function(a,c){for(var b=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=String(c).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(d.length,g.length),e=0;b==0&&e<h;e++){var f=d[e]||"",n=g[e]||"",i=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var l=i.exec(f)||["","",""],j=q.exec(n)||["","",""];if(l[0].length==0&&j[0].length==0)break;b=B(l[1].length==0?0:parseInt(l[1],10),j[1].length==0?0:parseInt(j[1],10))||B(l[2].length==0,j[2].length==0)||B(l[2],j[2])}while(b==
0)}return b},B=function(a,c){if(a<c)return-1;else if(a>c)return 1;return 0};var D,E,F,G,H,I=function(){return A.navigator?A.navigator.userAgent:m};H=G=F=E=D=o;var J;if(J=I()){var K=A.navigator;D=J.indexOf("Opera")==0;E=!D&&J.indexOf("MSIE")!=-1;G=(F=!D&&J.indexOf("WebKit")!=-1)&&J.indexOf("Mobile")!=-1;H=!D&&!F&&K.product=="Gecko"}var L=D,M=E,N=H,O=F,P=G,Q="",R;if(L&&A.opera){var S=A.opera.version;Q=typeof S=="function"?S():S}else{if(N)R=/rv\:([^\);]+)(\)|;)/;else if(M)R=/MSIE\s+([^\);]+)(\)|;)/;else if(O)R=/WebKit\/(\S+)/;if(R){var T=R.exec(I());Q=T?T[1]:""}}var U=Q,V={};var aa=function(a){var c=window;if(a&&window.top!=window)c=c.top;try{if(c.document&&!c.document.body)return"&bs=-1,-1";else{var b=c.document;if(O&&!(V["500"]||(V["500"]=C(U,"500")>=0))&&!P){var d=c.innerHeight,g=b.documentElement.scrollHeight;if(c==c.top)if(g<d)d-=15;return"&bs="+[c.innerWidth,d].join(",")}var h=b.compatMode=="CSS1Compat"&&(!L||L&&(V["9.50"]||(V["9.50"]=C(U,"9.50")>=0)))?b.documentElement:b.body;return"&bs="+[h.clientWidth,h.clientHeight].join(",")}}catch(e){return"&bs=-12245933,-12245933"}};function W(){var a=arguments;this.a={};this.t.apply(this,a)}W.prototype.o=500;var X={},ba=window.google.loader.createGuidArg_();W.prototype.d={w:650,mw:450,n1w0:300,n:240,nw:160};
W.prototype.j={query:"required",pubId:"required",container:"required",format:"optional",number:"optional",channel:"optional",colorText:"optional",colorTitleLink:"optional",colorDomainLink:"optional",colorBackground:"optional",colorBorder:"optional",hl:"optional",adtest:"optional",adsafe:"optional",linkTarget:"optional",oe:"optional",ie:"optional"};
W.prototype.e={query:"q",format:"format",ads:"ad",pubId:"client",channel:"channel",colors:{arg:"alt_color",colorText:"ct",colorTitleLink:"ctl",colorDomainLink:"cdl",colorBackground:"cbg",colorBorder:"cb"},adtest:"adtest",hl:"hl",adsafe:"adsafe",adPage:"adpage",linkTarget:"target",oe:"oe",ie:"ie",output:"output",res_url:"res_url",rurl:"rurl",nocache:"nocache",fexp:"fexp",num:"num",safe:"safe",source:"source"};
var ca=function(a,c,b){var d=function(g){g=g?g:window.event;if(g.source==c.contentWindow){if(window.detachEvent)window.detachEvent("onmessage",d);else window.removeEventListener&&window.removeEventListener("message",d,o);b(g.data)}};if(window.attachEvent)window.attachEvent("onmessage",d);else window.addEventListener&&window.addEventListener("message",d,o)},da=function(a,c,b){var d=function(){var g=0;try{var h=c.contentWindow;if(h.frames&&h.frames.length)g=h.frames[0].name}catch(e){}b(g)};if(r())c.onreadystatechange=
function(){if(c.readyState=="loaded"||c.readyState=="complete"){c.onreadystatechange=m;d()}};else c.onload=function(){c.onload=m;d()}},Y=function(a,c){a.b.style.fontWeight="normal";a.b.style.textAlign="center";a.b.innerHTML="";a.b.appendChild(c)};
W.prototype.t=function(){var a=(new Date).getTime();this.l=a%100==1?a:-1;a:{a=arguments;var c={};if(a&&!a.length)c=a;else if(a&&a.length==1)c=a[0];else if(a&&a.length==3){c=a[2];c.pubId=a[0];c.container=a[1]}else{a=void 0;break a}a=c}if(typeof a.logHandler=="function"||typeof a.dbg=="function")this.h=typeof a.logHandler=="function"?a.logHandler:a.dbg;if(this.a){a=a;for(var b in this.a)a[b]||(a[b]=this.a[b]);a=a;if(this.a.query==a.query){Z(this,"Cannot refresh the same query.");return}if((new Date).getTime()-
this.r<this.o){Z(this,"Ad refreshed too soon.");return}}a:{a=a;b={};for(var d in this.j)if(this.j[d]=="required"&&!a[d]){Z(this,"Missing '"+d+"'.");a=m;break a}else if(a[d])b[d]=a[d];d=b.container;if(typeof d=="string"){var g=" '"+d+"' ";d=document.getElementById(d)}if(!d)throw"google.ads.search.Ad: Container "+g+" does not exist";this.b=d;if(typeof this.b=="string"){Z(this,"Container does not exist");a=m}else{b.oe=b.oe||"UTF-8";b.ie=b.ie||"UTF-8";b.adtest=b.adtest||"nodebugip";b.number=b.number||
2;b.format=b.format||"wide";b.adsafe=b.adsafe||"high";b.nocache=(new Date).getTime();b.fexp="21404";b.num="0";b.safe="off";b.output="uds_ads_only";b.source="afs_ads_only";this.g=this.b.offsetWidth;switch(b.format.toLowerCase()){case "wide":if(this.g<this.d.mw){b.format="n1w0";b.ads="n1"}else{b.format=this.g<this.d.w?"mw":"w";b.ads="w"+b.number}break;case "narrow":b.format=this.g<this.d.n?"nw":"n";b.ads="n"+b.number;break;default:break}if(b.pubId.indexOf("partner-")==0){Z(this,"Do not add 'partner-' to the pubId.");
b.pubId=b.pubId.substring(8)}a=b}}if(a){this.a=a;if(this.h){g=this.a;Z(this,"Selected Options:");for(var h in g)if(g.hasOwnProperty(h)){if(h=="format"){d=this.a.format;d=d=="w"||d=="n1w0"?"wide":"narrow"}else d=g[h];Z(this,h+": "+d)}}g=a;h=[];for(var e in g)if(this.e[e]){d=this.e[e];b=g[e];if(e=="format"&&g[e]!="n1w0")b=g[e]+g.number;h.push([d,encodeURIComponent(b)].join("="))}e=this.e.colors.arg;d=[];for(var f in this.e.colors){b=this.e.colors[f];a=g[f]||m;f!="arg"&&a&&d.push([b,a].join(","))}if(d.length>
0){d=d.join("|");h.push([e,encodeURIComponent(d)].join("="))}h.push(ba);if(typeof X[this.a.query]=="undefined")X[this.a.query]=1;else{h.push("adpage="+X[this.a.query]);X[this.a.query]++}f=window.location.href||"";f=encodeURIComponent(f);e=window.document.referrer||"";e=encodeURIComponent(e);h.push("rurl="+f);h.push("referer="+e);f=window.google.loader.ServiceBase+"/afs?";f+=h.join("&");e=f=f.substring(0,2E3).replace(/%\w?$/,"");Z(this,"New url: "+e);f=document.createElement("iframe");f.name="google_afs_ads_frame";
f.frameBorder=0;f.marginWidth=0;f.marginHeight=0;f.vspace=0;f.hspace=0;f.u="true";f.scrolling="no";f.style.visibility="hidden";f.src=e;e=(e=window.navigator?window.navigator.userAgent:m)?u(e)==6:o;if(!(e=e))e=(e=window.navigator?window.navigator.userAgent:m)?u(e)==7:o;if(e=e){e=(e=window.navigator?window.navigator.userAgent:m)?/trident\/\d/i.test(e)&&u(e)==7:o;e=!e}if(e){Y(this,f);x(new p($(this,f),"parent",f))}else{e=$(this,f);h=window;(h.postMessage?h:h.document.postMessage?h.document:m)?ca(this,
f,e):da(this,f,e);Y(this,f)}}};
var $=function(a,c){return function(b){window.google.loader.recordStat("afsq","1");var d=a.a.format;c.width="100%";if(a.b.offsetWidth<a.d[d])a.b.style.width=a.d[d]+"px";if(b>40){c.style.visibility="visible";c.style.height=b+"px";a.b.style.height=b+"px"}else{c.style.height="0px";a.b.style.height="0px"}a.r=(new Date).getTime();b=document.createElement("img");d=window.google.loader.ServiceBase+"/stats?r0=afs_render";var g;g="&u_his="+window.history.length;var h="&u_tz="+-(new Date).getTimezoneOffset(),
e="&dt="+(new Date).getTime(),f="&u_w="+window.screen.width,n="&u_h="+window.screen.height,i=aa(),q;q="&ps=";var l=!window.scrollY&&document.compatMode!="CSS1Compat";q+=[l?document.body.scrollWidth:document.body.offsetWidth,l?document.body.scrollHeight:document.body.offsetHeight].join(",");q=q;var j=c;if(typeof j=="string")j=document.getElementById(j);l=z(j,k);j=z(j,o);l="&is="+[l,j].join(",");var t;a:{try{t=window!=window.top;break a}catch(ea){}t=k}b.src=d+[g,h,e,f,n,i,q,l,t?"&frm=1":"&frm=0"].join("");
b.style.display="none";a.b.appendChild(b);if((t=a.l)&&t!=-1){window.google.loader.recordStat("asa_ads_only","rur."+((new Date).getTime()-t),k);a.l=-1}}},Z=function(a,c){a.h&&a.h(c)};window.google=window.google||{};window.google.ads=window.google.ads||{};window.google.ads.search={Ad:W};
google.loader.loaded({"module":"ads","version":"1.0","components":["search"]});
google.loader.eval.ads = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['ads']) {(function() {var scripts = google.loader.eval.scripts['ads'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.ads(scripts[i]);}})();google.loader.eval.scripts['ads'] = null;}})();